"""empty message

Revision ID: 3a8b698f8109
Revises: 8f96fadd3594
Create Date: 2025-04-19 11:14:18.621423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8b698f8109'
down_revision = '8f96fadd3594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('image_data')
        batch_op.drop_column('label')

    # ### end Alembic commands ###
